name: Quality Gate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  quality-gate:
    name: Quality Gate - Zero Tolerance
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y make
      
    - name: Install cargo tools (skip if timeout)
      run: |
        echo "Installing cargo tools with timeout protection..."
        timeout 300 cargo install cargo-audit --quiet || echo "cargo-audit installation skipped due to timeout"
        timeout 300 cargo install cargo-tarpaulin --quiet || echo "cargo-tarpaulin installation skipped due to timeout"
      continue-on-error: true
        
    - name: Format Check
      run: make format-check
      
    - name: Lint Check
      run: make lint
      
    - name: Security Audit (if available)
      run: make security-audit || echo "Security audit skipped"
      continue-on-error: true
      
    - name: Dependency Check
      run: cargo tree --duplicates
      
    - name: Test Suite
      run: make test
      
    - name: Test Examples
      run: make test-examples
      
    - name: Coverage Analysis (if available)
      run: make coverage-stdout || echo "Coverage analysis skipped"
      continue-on-error: true
      
    - name: Build Release
      run: make build-release
      
    - name: Quality Gate Status
      run: echo "✅ All quality gates passed!"