name: Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: Build Release Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary-suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary-suffix: ".exe"
          - os: macOS-latest
            target: x86_64-apple-darwin
            binary-suffix: ""
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
        
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Build release binary
      run: cargo build --release --target ${{ matrix.target }}
      
    - name: Strip binary (Unix)
      if: matrix.os != 'windows-latest'
      run: strip target/${{ matrix.target }}/release/rclean${{ matrix.binary-suffix }}
      
    - name: Create archive
      shell: bash
      run: |
        staging="rclean-${{ matrix.target }}"
        mkdir -p "$staging"
        cp target/${{ matrix.target }}/release/rclean${{ matrix.binary-suffix }} "$staging/"
        cp README.md LICENSE CHANGELOG.md "$staging/"
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          7z a "$staging.zip" "$staging"
          echo "ASSET=$staging.zip" >> $GITHUB_ENV
        else
          tar czf "$staging.tar.gz" "$staging"
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
        fi
        
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.ASSET }}
        body: |
          Release ${{ github.ref_name }}
          
          See [CHANGELOG.md](CHANGELOG.md) for details.
        draft: false
        prerelease: false